package com.onyx.android.sdk.pennative

import android.graphics.Bitmap

/** Immutable native ink payload compatible with `onyxsdk-pennative:1.0.4`. */
class PenInk(
    /** Flat geometry records generated by the selected renderer. */
    val points: FloatArray,

    /** Number of floats in each logical record in [points]. */
    val pointSizeArray: IntArray,

    /** Raster stamps generated by bitmap-based pen types. */
    val bitmaps: Array<Bitmap>,
) {
    /** Returns a diagnostic representation containing the flattened [points]. */
    override fun toString(): String = buildString {
        append("PenInk: ${points.size} -> [")
        if (points.isNotEmpty()) append(points[0])
        for (index in 1 until points.size) append(",${points[index]}")
        append(']')
    }

    /** Java-friendly factory matching the vendor API. */
    companion object {
        /**
         * Creates an immutable ink payload from native geometry and raster output.
         *
         * The arrays are retained without copying to preserve the vendor ABI and allocation
         * behavior.
         */
        @JvmStatic
        fun create(
            points: FloatArray,
            pointSizeArray: IntArray,
            bitmaps: Array<Bitmap>,
        ): PenInk = PenInk(points, pointSizeArray, bitmaps)
    }
}
