// 
// 

package com.onyx.android.sdk.utils;

import java.util.Iterator;
import java.util.List;
import java.util.Collection;
import android.content.pm.ResolveInfo;
import android.content.pm.PackageManager;
import android.content.pm.ActivityInfo;
import android.content.Context;
import android.content.ComponentName;
import android.webkit.MimeTypeMap;
import android.net.Uri;
import com.onyx.android.sdk.common.provider.OnyxFileProviderUtil;
import android.content.Intent;
import java.io.File;

public class ViewDocumentUtils
{
    public static String ACTION_ENABLE_READER_DEBUG_LOG = "com.onyx.android.sdk.action_enable_reader_debug_log";
    public static String ACTION_DISABLE_READER_DEBUG_LOG = "com.onyx.android.sdk.action_disable_reader_debug_log";
    public static String TAG_AUTO_SLIDE_SHOW_MODE = "auto_slide_show";
    public static String TAG_SLIDE_SHOW_MAX_PAGE_COUNT = "slide_show_page_count";
    public static String TAG_SLIDE_SHOW_INTERVAL_IN_SECONDS = "slide_show_mode";
    
    public static Intent viewActionIntent(final File file) {
        final Intent intent = new Intent();
        OnyxFileProviderUtil.setIntentData(ResManager.getAppContext(), intent, file, true);
        intent.setAction("android.intent.action.VIEW");
        return intent;
    }
    
    public static Intent viewActionIntent(final File file, final int... flags) {
        final Intent viewActionIntent = viewActionIntent(file);
        if (flags != null && flags.length > 0) {
            for (int length = flags.length, i = 0; i < length; ++i) {
                viewActionIntent.addFlags(flags[i]);
            }
        }
        return viewActionIntent;
    }
    
    public static Intent autoSlideShowIntent(final File file, final int maxPageCount, final int intervalInSeconds) {
        final Intent viewActionIntentWithMimeType = viewActionIntentWithMimeType(file, new int[0]);
        viewActionIntentWithMimeType.setComponent(a());
        viewActionIntentWithMimeType.setFlags(268435456);
        viewActionIntentWithMimeType.putExtra(ViewDocumentUtils.TAG_AUTO_SLIDE_SHOW_MODE, true);
        viewActionIntentWithMimeType.putExtra(ViewDocumentUtils.TAG_SLIDE_SHOW_MAX_PAGE_COUNT, maxPageCount);
        viewActionIntentWithMimeType.putExtra(ViewDocumentUtils.TAG_SLIDE_SHOW_INTERVAL_IN_SECONDS, intervalInSeconds);
        return viewActionIntentWithMimeType;
    }
    
    public static Intent intentFromMimeType(final File file) {
        final Intent viewActionIntent = viewActionIntent(file);
        final String fileMimeType;
        if (!StringUtils.isNullOrEmpty(fileMimeType = getFileMimeType(file))) {
            if (CompatibilityUtil.apiLevelCheck(24)) {
                final Intent intent = viewActionIntent;
                intent.setDataAndType(intent.getData(), fileMimeType);
            }
            else {
                viewActionIntent.setDataAndType(Uri.fromFile(file), fileMimeType);
            }
        }
        else {
            viewActionIntent.setData(Uri.fromFile(new File("dummy." + FileUtils.getFileExtension(file))));
            Debug.w("query intent generated by dummy file. " + viewActionIntent);
        }
        return viewActionIntent;
    }
    
    public static String getFileMimeType(final File file) {
        final String fileExtension;
        String s;
        if (StringUtils.isNullOrEmpty(s = MimeTypeUtils.mimeType(fileExtension = FileUtils.getFileExtension(file)))) {
            s = MimeTypeMap.getSingleton().getMimeTypeFromExtension(fileExtension);
        }
        return s;
    }
    
    public static Intent viewActionIntentWithMimeType(final File file, final int... flags) {
        final Intent viewActionIntent = viewActionIntent(file, flags);
        final String fileMimeType;
        if (StringUtils.isNotBlank(fileMimeType = getFileMimeType(file))) {
            final Intent intent = viewActionIntent;
            intent.setDataAndType(intent.getData(), fileMimeType);
        }
        return viewActionIntent;
    }
    
    public static Intent enableReaderDebugLogIntent() {
        return new Intent(ViewDocumentUtils.ACTION_ENABLE_READER_DEBUG_LOG);
    }
    
    public static Intent disableReaderDebugLogIntent() {
        return new Intent(ViewDocumentUtils.ACTION_DISABLE_READER_DEBUG_LOG);
    }
    
    private static ComponentName a() {
        return new ComponentName("com.onyx.kreader", "com.onyx.kreader" + ".ui.ReaderTabHostActivity");
    }
    
    public static ComponentName getReaderComponentName(final Context context) {
        return getReaderComponentName(context, a());
    }
    
    public static ComponentName getEduReaderComponentName() {
        return new ComponentName("com.onyx.edu.reader", "com.onyx.edu.reader" + ".ui.ReaderTabHostActivity");
    }
    
    public static ComponentName getEduReaderComponentName(final Context context) {
        return getReaderComponentName(context, getEduReaderComponentName());
    }
    
    public static ComponentName getReaderComponentName(Context context, final ComponentName componentName) {
        ActivityInfo info = null;
        try {
            info = context.getPackageManager().getActivityInfo(componentName, 0);
        }
        catch (final PackageManager.NameNotFoundException ex) {
            ex.printStackTrace();
        }
        if (info == null) {
            return null;
        }
        return componentName;
    }
    
    public static ResolveInfo getDefaultActivityInfo(final Context context, final File file, final String defaultPackageName) {
        return getDefaultActivityInfo(context, viewActionIntent(file), defaultPackageName);
    }
    
    public static ResolveInfo getDefaultActivityInfo(final Context context, final Intent intent, final String defaultPackageName) {
        final List queryIntentActivities;
        if (CollectionUtils.isNullOrEmpty(queryIntentActivities = context.getPackageManager().queryIntentActivities(intent, 65536))) {
            return null;
        }
        if (StringUtils.isNullOrEmpty(defaultPackageName)) {
            return (ResolveInfo)queryIntentActivities.get(0);
        }
        final Iterator iterator = queryIntentActivities.iterator();
        while (iterator.hasNext()) {
            final ResolveInfo resolveInfo;
            if ((resolveInfo = (ResolveInfo)iterator.next()).activityInfo.packageName.equals(defaultPackageName)) {
                return resolveInfo;
            }
        }
        return (ResolveInfo)queryIntentActivities.get(0);
    }
}
