config:
  validation: true
  excludes: 'HbmartinRuleSet.*,HbmartinRuleSet>.*>.*'

HbmartinRuleSet:
  excludes:
    - '**/test/**'
    - '**/androidTest/**'
    - '**/commonTest/**'
    - '**/jvmTest/**'
    - '**/androidUnitTest/**'
    - '**/androidInstrumentedTest/**'
    - '**/jsTest/**'
    - '**/iosTest/**'
  AvoidFirstOrLastOnList:
    active: true
    methods:
      - 'first'
      - 'last'
      - 'single'
      - 'elementAt'
      - 'reduce'
      - 'reduceRight'
      - 'max'
      - 'min'
      - 'maxBy'
      - 'minBy'
  AvoidGlobalScope:
    active: true
  AvoidMutableCollections:
    active: true
    allowPrivateAndLocal: false
    excludes:
      - '**/build-logic/src/main/kotlin/AndroidConvention.kt'
      - '**/build-logic/src/main/kotlin/OnyxDeviceValidationPlugin.kt'
  AvoidToIntOrThrowingConversions:
    active: true
    methods:
      - 'toInt'
      - 'toLong'
      - 'toShort'
      - 'toByte'
      - 'toDouble'
      - 'toFloat'
      - 'toUInt'
      - 'toULong'
      - 'toUShort'
      - 'toUByte'
      - 'toBigDecimal'
      - 'toBigInteger'
      - 'toBooleanStrict'
  AvoidVarsExceptWithDelegate:
    active: true
    allowedDelegates:
      - 'remember\w*'
      - 'mutableState\w*'
  DontForceCast:
    active: true
  MutableTypeShouldBePrivate:
    active: true
    allowedTypes: []
  NoCallbacksInFunctions:
    active: true
    ignoreAnnotated: ['Composable']
    allowExtensions: true
    allowReceivers: true
    allowInline: false
    excludes:
      - '**/com/onyx/android/sdk/base/data/Size.kt'
      - '**/com/onyx/android/sdk/ktx/RawInputEvent.kt'
  NoDeferredResultInPublicApi:
    active: true
  NoLateinitVar:
    active: true
    allowedAnnotations: []
  NoNotNullOperator:
    active: true
  NoRunBlocking:
    active: true
  NoVarsInConstructor:
    active: true
    excludes:
      - '**/com/onyx/android/sdk/base/data/Size.kt'
      - '**/com/onyx/android/sdk/pen/PenBrushInk.kt'
  WhenBranchSingleLineOrBraces:
    active: true
